name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@4
      - user: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci

      - run: npm test
